### ISSUE TITLE
TS for the New Programmer 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#111]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/tutorials/ts-for-the-new-programmer.md)

**Comment by samsara-ku** [comment]
제가 번역 시도 해보겠습니다.

예상 완료 날짜: 2020. 08. 7
번역 범위: `What is JavaScript? A Brief History` 까지

**Comment by Bumkeyy** [comment]
@samsara-ku 

[Contributing Guide](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/CONTRIBUTING.md)를 참고해서 번역해주세요 😄

**Comment by samsara-ku** [comment]
나머지 번역 제가 시도하겠습니다.

* 예상 완료 날짜: 2020. 08. 14
* 번역 범위: 문서 전체

**Comment by samsara-ku** [comment]
번역상의 질문이 있으나, PR을 날리기에는 문서를 전체 번역하지 못해서 질문 여기다 남기겠습니다.

다음과 같은 문장이 있습니다.

```
-If you move some code from a JavaScript file to a TypeScript file, you might see _type errors_ depending on how the code is written.
-These may be legitimate problems with the code, or TypeScript being overly conservative.
```

스스로 윗 문장을 해석한 바로는, JS코드를 TS코드로 migration 시킬 때 오류가 생길 수도 아닐 수도 있다는 의미라고 생각했습니다.

그렇기에 아래 문장을 해석했을 때, 다음과 같이 의역을 했습니다.

`이는 코드상의 문제이거나, TypeScript의 타입 검사가 지나치게 엄격한 것일 수 있습니다.`

영어로 `legitimate problems with the code`를 직역하면 `합법적인 코드의 문제`인데, 저는 이걸 "코드의 자체적인 문제"라고 생각합니다. 코드의 로직이 잘못된 것과 같은 "코드가 잘못된 경우"가 아닐까요.

또 `TypeScript being overly conservative`은 `보수적`의 의미가 아마 JS에 비해 TS가 type checking을 하기 때문에 static type checking을 지원하는 C, C++등을 대신한다는 의미에서 저렇게 표현했다고 생각하고 저렇게 의역했습니다.

어떻게 해석하면 좋을까요? 번역에 대해 도움 부탁드립니다.

**Comment by guyeol** [comment]
@samsara-ku 님께서 번역하신 문장이 원어에서 전달하고자 하는 의미와 맞는 것 같습니다
그대로 진행하셔도 괜찮을 것 같고, 두 번째 문장의 경우 직역으로
`TypeScript가 지나치게 보수적인 것일 수 있습니다`
로 해도 저는 괜찮아보입니다
