### ISSUE TITLE
TS for JS Programmers 번역 필요

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#112]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/tutorials/ts-for-js-programmers.md)

**Comment by ssMinji** [comment]
이 부분 제가 번역해보도록 할게요! :) 
예상 종료 일정: 08/14

**Comment by samsara-ku** [comment]
나머지 부분 제가 번역하겠습니다.
예상 종료 일정: 09/04
번역 범위: 문서 전체

**Comment by samsara-ku** [comment]
멘토님들 질문이 하나 있습니다.

이번에 번역에 리뷰가 작성되어서 해당 내용 적용하고 다시 푸시하는데 다음과 같이 커밋로그가 뜨네요.

원래 `나머지 부분 번역`이라는 커밋이 이전에 존재했었는데, 이번에 `리뷰 내용에 맞추어서 수정`이라는 커밋을 새로 추가해서 푸시하니까, 이번에 새로 등록된 커밋같이 커밋로그가 남네요.

제가 생각했을 때, 원래는 적용되어있던 커밋이므로 이번에 새로 등록된 `리뷰 내용에 맞추어서 수정`이라는 커밋만 남아야한다고 생각합니다.

왜 그런지 알 수 있을까요?

![image](https://user-images.githubusercontent.com/59246456/92293381-19616900-ef5e-11ea-83be-6ed0a6902a08.png)

**Comment by Bumkeyy** [comment]
> 멘토님들 질문이 하나 있습니다.
> 
> 이번에 번역에 리뷰가 작성되어서 해당 내용 적용하고 다시 푸시하는데 아래의 이미지와 같이 커밋로그가 뜨네요.
> 
> 원래 `나머지 부분 번역`이라는 커밋이 이전에 존재했었는데, 이번에 `리뷰 내용에 맞추어서 수정`이라는 커밋을 새로 추가해서 푸시하니까, 이번에 새로 등록된 커밋같이 커밋로그가 남네요.
> 
> 제가 생각했을 때, 원래는 적용되어있던 커밋이므로 이번에 새로 등록된 `리뷰 내용에 맞추어서 수정`이라는 커밋만 남아야 한다고 생각합니다.
> 
> 왜 그런지 알 수 있을까요?
> 
> ![image](https://user-images.githubusercontent.com/59246456/92293381-19616900-ef5e-11ea-83be-6ed0a6902a08.png)

혹시 push --force를 하셨나요? 
그래서 commit의 hash값이 변경되어 새로운 커밋으로 등록된 것 같아요 :)
