### ISSUE TITLE
TS for OOP Programmers 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#113]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/tutorials/ts-for-oopers.md)

**Comment by SeokHyeonChin** [comment]
우선 조금만 시도해 봐도 괜찮을까요?

- 예상 완료 날짜: 2020. 08. 15

- 번역 범위: Co-learning JavaScript 문단까지 ( ~ Don't limit yourself to TypeScript-specific resources! )

**Comment by SeokHyeonChin** [comment]
깃허브 사용법이 익숙하지 않아서 생각보다 시간이 더 걸리네요 ㅠ 
시간 하루만 더 연장해도 괜찮을까요? 

- 예상 완료 날짜 변경: 2020. 08. 16

**Comment by Bumkeyy** [comment]
> 깃허브 사용법이 익숙하지 않아서 생각보다 시간이 더 걸리네요 ㅠ
> 시간 하루만 더 연장해도 괜찮을까요?
> 
> * 예상 완료 날짜 변경: 2020. 08. 16

네~ 혹시 문제가 생기면 여기에 알려주세요 :)

**Comment by SeokHyeonChin** [comment]
일부 더 번역하겠습니다!

예상 완료 날짜: 2020. 08. 19

번역 범위: Types as Sets 문단까지 ( ~ and you'll find them more intuitive if you think of types as sets.)

**Comment by SeokHyeonChin** [comment]
직전에 해석한 마크다운 파일에서 마지막 문단 '런타임' 부분에 문제가 있었네요 ㅎㅎ.. 
이 부분도 같이 이탈릭체로 수정하도록 하겠습니다!

**Comment by SeokHyeonChin** [comment]
#153

**Comment by samsara-ku** [comment]
나머지 번역 신청하겠습니다~

예상 완료 날짜: 2020. 09. 11

번역 범위: 문서 전체
