### ISSUE TITLE
TS for Functional Programmers

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#114]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/tutorials/ts-for-functional-programmers.md)

**Comment by annkimm** [comment]
제가 번역해봐도 괜찮을까요?

- 예상 완료 날짜: 2020. 08. 23
- 번역 범위: 문서 전체

**Comment by annkimm** [comment]
> 제가 번역해봐도 괜찮을까요?
> 
> * 예상 완료 날짜: 2020. 08. 23
> * 번역 범위: 문서 전체

제가 23일을 완료 잡았는데 생각보다 타이트하게 잡은거 같아서 일정을 조정해도 될까요?
만약에 된다면

- 예상 완료 날짜: 2020. 08. 26
- 번역 범위: 문서 전체

@dvlprsh

**Comment by dvlprsh** [comment]
@annkimm 
넵! 일정 조정 하셔도 됩니다 :)
혹시 다른 문제생기면 언제든지 알려주세요~
