### ISSUE TITLE
Unions and Intersection 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#116]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/unions-and-intersections.md)

> 기존의 [고급 타입](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/advanced-types.md)와 같이 수정 및 번역 필요

**Comment by zigsong** [comment]
번역 신청하겠습니다! 

- 예상 날짜: 8/20
- 번역 범위: 전부

**Comment by zigsong** [comment]
@Bumkeyy 실수로 잘못 눌러서 assignee를 해제했는데 다시 assign myself가 안 되네요..! 권한이 제게 없는 것 같은데 assign해주시면 감사하겠습니다!

**Comment by zigsong** [comment]
@Bumkeyy 또 이 부분의 경우 [고급 타입](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/advanced-types.md)을 참고하라고 해주셨는데, 해당 문서와 정확히 일치하는 구문이지만 번역에 비문이나 부자연스러운 문장이 있으면 제가 수정해서 써도 되는 것인가요?

**Comment by Bumkeyy** [comment]
@

> @Bumkeyy 또 이 부분의 경우 [고급 타입](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/advanced-types.md)을 참고하라고 해주셨는데, 해당 문서와 정확히 일치하는 구문이지만 번역에 비문이나 부자연스러운 문장이 있으면 제가 수정해서 써도 되는 것인가요?

네! 더 좋은 번역이 있다면 수정해주세요 😄
