### ISSUE TITLE
Dom Manipulation 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#117]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/tutorials/dom-manipulation.md)

**Comment by ss-won** [comment]
이쪽 파트 번역 해보겠습니다. 🙇🏻‍♀️

- 예상 날짜: 2020. 08. 19

- 번역 범위: 처음 ~ The Document Interface 파트

**Comment by sooyun429** [comment]
오픈소스 경험이 없어서 저한테는 조금 어렵지만.. ㅠㅠ 번역 한 번 진행해볼게요..!
예상 날짜: 2020. 08. 20
번역 범위: The Document Interface 다음(The Node interface) 파트

**Comment by ss-won** [comment]
나머지 파트 이어서 다 번역하겠습니다~~!~!~✋
- 예상완료날짜: 2020.09.08
- 번역 범위: Difference between `children` and `childNodes` 단락 ~ 끝까지
