### ISSUE TITLE
Babel with TypeScript 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#118]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/tutorials/babel-with-typescript.md)

**Comment by seohyun0120** [comment]
이 부분 제가 번역해보겠습니다. :) 
- 예상 날짜: 08.17 (처음 시도해보는거라 일단 길게 잡았습니다.)
- 번역 범위: 전부
