### ISSUE TITLE
JSDoc Reference 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#120]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/jsdoc-reference.md)

**Comment by owjs3901** [comment]
번역 신청합니다!!
예상 완료 날짜: 8/19

**Comment by owjs3901** [comment]
하나의 페이지를 모두 번역하지 못해서 죄송합니다, 제 번역 스킬을 조금 더 정검한 다음에 빠른 시일내에 나머지 페이지도 번역에 도전하도록 하겠습니다.
감사합니다.

**Comment by SeokHyeonChin** [comment]
번역 신청합니다!

예상 완료 날짜: 2020. 09. 11

번역 범위: 문서 나머지 전체
