### ISSUE TITLE
Creating DTS from JS 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#121]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/declaration-files/creating-dts-files-from-js.md)

**Comment by samsara-ku** [comment]
번역 신청합니다.

* 예상 완료 날짜: 2020. 08. 20
* 번역 범위: 문서 전체

**Comment by samsara-ku** [comment]
@Bumkeyy 님, 해당 issue close시켜주실 수 있으신가요? PR이 approved인데 아직 남아있습니다.

**Comment by Bumkeyy** [comment]
> @Bumkeyy 님, 해당 issue close시켜주실 수 있으신가요? PR이 approved인데 아직 남아있습니다.

수고하셨습니다 👍
