### ISSUE TITLE
The Handbook 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#122]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/the-handbook.md)

**Comment by sangminK** [comment]
이 부분 번역해보겠습니다.
예상 종료 일정: 08/16
범위: About this Handbook 까지

**Comment by sangminK** [comment]
두 번째 문단 번역하겠습니다.
예상 종료 일정 : 08/30
범위 : How is this Handbook Structured 파트

**Comment by sangminK** [comment]
이 부분 끝까지 번역해 보겠습니다.
예상 종료 일정  : 9/4 (금)

**Comment by sangminK** [comment]
윈도우 쓰는 사람은 
PR 날리기 전에 미리 npm 으로 돌려볼 수가 있나요???

**Comment by sangminK** [comment]
윈도우 쓰는데
PR 날리기 전에 npm 으로 돌려볼 수가 있나요???
로컬에서 번역한게 마크다운이나 링크가 잘 걸리는지 보고 싶은데
어떻게 봐야할지 모르겠네요
첫 시간에 윈도우라서 AWS 서버 써서 로컬 띄우는 것 했었는데 번역하는 건 로컬에서 해야 하지 않나요???
궁금합니다!! ㅎㅎ

**Comment by dvlprsh** [comment]
@sangminK
로컬에서 번역한 다음, 결과물을 aws ec2 서버로 받아와서 돌려볼 수 있습니다.
ec2 서버로 번역한 내용을 받아오는 방법은 두 가지가 있습니다:
1. `https://github.com/typescript-kr/typescript-kr.github.io`로 PR을 날린 뒤 PR한 내용을 ec2 에서 fetch 하는 방법
2. fork 한 저장소를 ec2로 clone 하는 방법


PR 날리기 전에 돌려보시려면... 1번 방법대로 하셔야 하는데요.
번역한 내용 `fork한 레포`에 push -> `fork한 레포`를 (실습시간에 한 방식대로) aws ec2 서버에서 clone해서 돌려보시면 될 거 같습니다.
다만, 다시 clone 받기 번거로우니 2번 방법으로
PR 날린 후 -> PR 한 내용을 aws ec2 서버 내의 로컬 git으로 fetch 해서 돌리는 방법이 낫지 않을까 싶습니다.

리모트 저장소에 PR한 내용을 fetch 하는 방법은 [이 자료](https://stackoverflow.com/questions/14947789/github-clone-from-pull-request)를 참고하시면 될 거 같습니다.

실습시간에 ec2에 clone 한 저장소에서
`git fetch origin pull/(PR 번호)/head:(브랜치 이름)`
이렇게 하시면 PR한 결과물을 로컬 git 브랜치로 받아올 수 있습니다.
(이때 origin url은 `https://github.com/typescript-kr/typescript-kr.github.io`로 되어 있어야 합니다.)

예) `git fetch origin pull/172/head:pr-test`를 실행하면 [#172 PR](https://github.com/typescript-kr/typescript-kr.github.io/pull/172)을 로컬 git의 `pr-test`브랜치로 받아올 수 있습니다.

하다가 막히는 부분 있으시면 연락 주세요 :)
