### ISSUE TITLE
TS for the New Programmer 마크다운 부분의 오류

### ISSUE THREAD

**Issue by samsara-ku** [typescript-kr/typescript-kr.github.io#133]
* 내용: [Typescript Handbook](https://typescript-kr.github.io/pages/tutorials/ts-for-the-new-programmer.html) 한글버전에 올라와있는 문제입니다.

업로드한 이미지에서 다음의 내용을 가지고 있는 code block이 마크다운이 정상적이나, 렌더링에서 꼬인 모습을 보이고 있습니다.

```
ts twoslash // @errors: 2551 const obj = { width: 10, height: 15 }; const area = obj.width * obj.heigth;
```

해당 내용 예전에 제가 블로그 마크다운할 때, 여러 번 있었던 문제였는데 어떻게 해결할 지 모르겠네요. 해결해주실 수 있나요?

<img width="980" alt="스크린샷 2020-08-10 오후 10 15 09" src="https://user-images.githubusercontent.com/59246456/89787092-e347e980-db57-11ea-9ddd-291cd1f9a4f5.png">

**Comment by samsara-ku** [comment]
위의 문제와 관련있는 코드라인은 다음과 같습니다.

```
```ts twoslash
// @errors: 2551
const obj = { width: 10, height: 15 };
const area = obj.width * obj.heigth;
```

### A Typed Superset of JavaScript

How does TypeScript relate to JavaScript, though?

#### Syntax

TypeScript is a language that is a _superset_ of JavaScript: JS syntax is therefore legal TS.
Syntax refers to the way we write text to form a program.
For example, this code has a _syntax_ error because it's missing a `)`:

```ts twoslash
// @errors: 1005
let a = (4
```
```

**Comment by Bumkeyy** [comment]
@samsara-ku 

아마 gitbook-cli 에서 code block에 `twoslash`를 파싱하지 못해 생기는 오류같아요.
해당 code block에 `twoslash`를 제거하면 제대로 보일 것 같습니다.

번역하면서 같이 수정해주시겠어요?😃

**Comment by samsara-ku** [comment]
해당 내용 적용하니 마크다운은 적용되지만, 다음과 같이 마크다운에 적용되는 스타일은 없어지게 되네요. 어떻게 해야할까요?

아 또한 추가적인 질문이 있습니다! 

추가한 이미지에서 볼 수 있듯이, 타입스크립트 영문 핸드북의 동일한 문서는 이슈에 제가 업로드한 이미지와 다르게 오류 부분에 대한 내용이 자세히 나와있는 것을 볼 수 있습니다.

해당 내용을 위의 `@errors: 1005`과 같은 부분을 갈음해서 번역하면 될까요?

![image](https://user-images.githubusercontent.com/59246456/89792848-0bd3e180-db60-11ea-8edd-02ace76febc4.png)

**Comment by Bumkeyy** [comment]
@samsara-ku 

최대한 빨리 해결해야겠네요...
일단 `@errors: 1005`는 남겨놓는게 어떨까요?

전 나중에 twoslash 적용이 될 때
다시 바꾸거나 추가하는 것보다 일단은 있는게 나을 것 같습니다.

@guyeol @dvlprsh 
어떻게 생각하세요?

**Comment by dvlprsh** [comment]
@Bumkeyy @samsara-ku 

> 일단 `@errors: 1005`는 남겨놓는게 어떨까요?
> 
> 전 나중에 twoslash 적용이 될 때
> 다시 바꾸거나 추가하는 것보다 일단은 있는게 나을 것 같습니다.

동의합니다 :)

**Comment by guyeol** [comment]
> @samsara-ku
> 
> 최대한 빨리 해결해야겠네요...
> 일단 `@errors: 1005`는 남겨놓는게 어떨까요?
> 
> 전 나중에 twoslash 적용이 될 때
> 다시 바꾸거나 추가하는 것보다 일단은 있는게 나을 것 같습니다.
> 
> @guyeol @dvlprsh
> 어떻게 생각하세요?

현재 상황에서 [ts-twoslasher](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/ts-twoslasher)를 해결하기는 어려우니 파싱에러만 해결하고 일단 남기는것에 동의합니다 추후 수정할 때가 왔을 때 그게 더 편할 것 같네요

**Comment by Bumkeyy** [comment]
해당 이슈는 일정 해결된걸로 보고 클로즈하겠습니다 :)
