### ISSUE TITLE
Pull Request template에 관한 건의

### ISSUE THREAD

**Issue by samsara-ku** [typescript-kr/typescript-kr.github.io#137]
* 내용: 

현재 타입스크립트 핸드북 github에는 issue의 템플릿은 존재하나, PR에 관련된 템플릿은 없는 것으로 알고 있습니다.

컨트리뷰터분들께서 조금 더 쉽고 나은 컨트리뷰팅에 필요하다고 생각하게 되어서 이슈를 새로 생성했습니다.

아래는 제가 짧게나마 구글링해본 PR template입니다. 이 중 하나를 고르거나, 아니면 절충안을 만들어서 한국어로 번역 후 적용하는게 좋을 것 같습니다.

개인적으로, axios template을 기반으로 수정하면 좋을 것 같습니다.

[webpack PR template](https://github.com/webpack/webpack/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

[babel PR template](https://github.com/babel/babel/blob/main/.github/PULL_REQUEST_TEMPLATE.md)

[jest PR template](https://github.com/facebook/jest/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

[mocha PR template](https://github.com/mochajs/mocha/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

[axios PR template](https://github.com/axios/axios/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

의견 남겨주시면 감사하겠습니다

**Comment by yeonjuan** [comment]
> 컨트리뷰터분들께서 조금 더 쉽고 나은 컨트리뷰팅에 필요하다고 생각하게 되어서 ...

안녕하세요 @samsara-ku :)  PR 템플릿에 어떤 내용이 들어가면,  이 기능을 할 수 있을까요??

**Comment by samsara-ku** [comment]
네, 안녕하세요 @yeonjuan 님!

제가 생각했을때는,

1. PR을 날리기 전에 `CONTRIBUTING.md`를 다시 확인하고 오라는 내용(axios폼을 참고하면 될 것 같습니다)과
2. Maintainer분들의 쉽고 빠른 이해를 위해 PR 타입(bug, docs, typo..)이 있으면 좋을 것 같고,
3. PR을 날리게 된 간단한 `배경 설명`과 `코드 설명`도 필요할 것 같습니다.

혹시 더 필요한 내용 있을까요?

**Comment by Bumkeyy** [comment]
> 네, 안녕하세요 @yeonjuan 님!
> 
> 제가 생각했을때는,
> 
> 1. PR을 날리기 전에 `CONTRIBUTING.md`를 다시 확인하고 오라는 내용(axios폼을 참고하면 될 것 같습니다)과
> 2. Maintainer분들의 쉽고 빠른 이해를 위해 PR 타입(bug, docs, typo..)이 있으면 좋을 것 같고,
> 3. PR을 날리게 된 간단한 `배경 설명`과 `코드 설명`도 필요할 것 같습니다.
> 
> 혹시 더 필요한 내용 있을까요?

여기에 [DefinitelyTyped PR Template](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/PULL_REQUEST_TEMPLATE.md) 처럼 **check box** 형식으로 PR 전에 직접 확인할 수 있도록 유도해도 좋을 것 같아요 :)

**Comment by yeonjuan** [comment]
> 제가 생각했을때는,
PR을 날리기 전에 CONTRIBUTING.md를 다시 확인하고 오라는 내용(axios폼을 참고하면 될 것 같습니다)과
Maintainer분들의 쉽고 빠른 이해를 위해 PR 타입(bug, docs, typo..)이 있으면 좋을 것 같고,
PR을 날리게 된 간단한 배경 설명과 코드 설명도 필요할 것 같습니다.
혹시 더 필요한 내용 있을까요?


@samsara-ku 넵 좋은 것 같습니다 :) 이견없어요. 너무 복잡하지는 않았으면 좋겠어요 👍
