### ISSUE TITLE
메인화면 프로필이 짤려보여요. 

### ISSUE THREAD

**Issue by jiimy** [typescript-kr/typescript-kr.github.io#184]
* 내용: 
https://typescript-kr.github.io/
이 주소에 '컨트리뷰터 목록'을 보면 우측에 프로필이 짤려보이는데 
.markdown-section table 여기에 
table-layout : fixed를 주면 맞게 나와요.

**Comment by guyeol** [comment]
@jiimy 님 이슈 감사합니다 👍 
말씀하신 이슈 확인했습니다!
혹시 직접 수정하실 의향이 있으시다면 PR 요청드려도 될까요??

**Comment by jiimy** [comment]
네 요청 드릴께요
 
 
-----Original Message-----
