### ISSUE TITLE
Path Mapping 번역 오류 제보

### ISSUE THREAD

**Issue by hanameee** [typescript-kr/typescript-kr.github.io#197]
안녕하세요 :) 핸드북 감사히 잘 참고하고 있습니다! 잘못 번역된 부분이 있는 것 같아 이슈를 남깁니다.

* 파일 경로 또는 링크: https://typescript-kr.github.io/pages/module-resolution.html#path-mapping

* 내용: Path mapping 부분의 코드 예시와 밑의 한글 해설이 일치하지 않는 것 같습니다. 코드에서는 baseUrl을 `"."` 로 설정하고 있는데, 글에서는 `위 예제에서 "baseUrl": "./src"로 설정했기 때문에` 라고 작성되어 있습니다. [원문](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#path-mapping)을 보니, baseUrl을 `./node_modules` 로 지정하고 있는데, 원문과 동일하게 예제와 글을 수정하면 혼선이 줄어들 것 같습니다. 수정을 해도 괜찮을까요?

* 직접 PR 하시겠습니까? (O/X): O

**Comment by Bumkeyy** [comment]
@hanameee 

안녕하세요 :)
오역을 발견해주셔서 감사합니다!

원문을 확인해보니 
> 내용: Path mapping 부분의 코드 예시와 밑의 한글 해설이 일치하지 않는 것 같습니다. 코드에서는 baseUrl을 "." 로 설정하고 있는데, 글에서는 위 예제에서 "baseUrl": "./src"로 설정했기 때문에 라고 작성되어 있습니다. 원문을 보니, baseUrl을 ./node_modules 로 지정하고 있는데, 원문과 동일하게 예제와 글을 수정하면 혼선이 줄어들 것 같습니다. 수정을 해도 괜찮을까요?

`"baseUrl": "./src"로 설정했기 때문에` 가 아닌 ` "baseUrl": "./src"로 설정한다면`이 옳은 번역이라고 생각이 됩니다.
원문 링크는 TypeScript 2.0 릴리즈 페이지를 가리키고 있어 오역이 있는 문서와는 위치가 다른 것 같습니다 😄 

원문 링크는 [module-resolution#path-mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping)을 확인하시면 될 것 같아요!

**Comment by hanameee** [comment]
엇! 제가 버전이 다른 원문을 보고 있었군요. 알려주셔서 감사합니다 (_ _)
알려주신 원문 링크를 읽어보니 해석이
>  Say, you set "baseUrl": "./src" in the above example, then jquery should be mapped to "../node_modules/jquery/dist/jquery".

원문이 위와 같이 되어있는데, 해석이
>  위 예제에서 "baseUrl": "./src"로 설정했기 때문에, jquery는 "../node_modules/jquery/dist/jquery"로 매핑됩니다.

이렇게 되어 있는데요!
이보다는
> 만약 위 예제에서 "baseUrl": "./src" 로 설정한다면, jquery는 "../node_modules/jquery/dist/jquery" 로 매핑되어야 합니다.
 
이 해석이 더 적절할 것 같습니다. 전체 프로젝트 구조가 root 하에 src도 있고, node_modules도 있는 상황에서 (예제 코드) `"baseUrl": "."` 로 설정했을때는 매핑을 "/node_modules/jquery/dist/jquery" 로, (밑의 문단) `"baseUrl": "./src"` 로 설정했을때는 매핑을 "../node_modules/jquery/dist/jquery" 로 변경해야 한다는 것을 알려주고자 하는 것 같아서요!

**Comment by Bumkeyy** [comment]
> 엇! 제가 버전이 다른 원문을 보고 있었군요. 알려주셔서 감사합니다 (_ _)
> 
> 알려주신 링크에서 원문을 읽어보니
> 
> >  Say, you set "baseUrl": "./src" in the above example, then jquery should be mapped to "../node_modules/jquery/dist/jquery".
> 
> 
> 
> 위와 같이 되어있는데, 이에 대한 해석이
> 
> >  위 예제에서 "baseUrl": "./src"로 설정했기 때문에, jquery는 "../node_modules/jquery/dist/jquery"로 매핑됩니다.
> 
> 
> 
> 이렇게 되어 있는데요!
> 
> 이보다는
> 
> > 만약 위 예제에서 "baseUrl": "./src" 로 설정한다면, jquery는 "../node_modules/jquery/dist/jquery" 로 매핑되어야 합니다.
> 
>  
> 
> 이 해석이 더 적절할 것 같습니다. 전체 프로젝트 구조가 root 하에 src도 있고, node_modules도 있는 상황에서 (예제 코드) `"baseUrl": "."` 로 설정했을때는 매핑을 "/node_modules/jquery/dist/jquery" 로, (밑의 문단) `"baseUrl": "./src"` 로 설정했을때는 매핑을 "../node_modules/jquery/dist/jquery" 로 변경해야 한다는 것을 알려주고자 하는 것 같아서요!

동의합니다 :)
PR 기다릴게요 ㅎㅎ

**Comment by hanameee** [comment]
넵! PR 날렸습니다 :D
