### ISSUE TITLE
오타 수정 요청

### ISSUE THREAD

**Issue by Yangeok** [typescript-kr/typescript-kr.github.io#22]
안녕하세요. 

`typescript-kr.github.io / pages / tutorials / React & Webpack.md`

위 파일에서 라인 87에 있는 __입이다.__를 __입니다.__로 오타 수정 요청드립니다.

**Comment by devJang** [comment]
안녕하세요
@Yangeok  님
늦은 이슈 확인 죄송합니다!

현재 최신 TypeScript 핸드북을 번역하시는 분들이 계시기 때문에
그 분들과 함께하여 새롭게 작성된 번역본으로 마이그레이션할 예정입니다.

이 과정에서 제기하신 이슈가 해결될 수 있고 클로즈처리 될 수 있을 것 같으니
잠시만 기다려주세요!

**Comment by Bumkeyy** [comment]
해당 오타는 새롭게 번역된 문서를 마이그레이션 하면서 해결되었습니다.

감사합니다 😄
