### ISSUE TITLE
버튼 겹침

### ISSUE THREAD

**Issue by Hansanghyeon** [typescript-kr/typescript-kr.github.io#27]
다음글로 넘어가는 버튼과 Fork me github 이미지랑 겹치는 부분이있어서
github으로 넘어올려했는데 다음페이지로 넘어가서 처음에는 오류인줄알았습니다.

수정되면 좋을것같습니다

**Comment by notoriousmango** [comment]
@Hansanghyeon 어느 페이지를 말씀하시는 거죠?

**Comment by Hansanghyeon** [comment]
![](https://cdn4log.s3.ap-northeast-2.amazonaws.com/images/screen.png)

데스크탑에서 전체인 것같습니다

**Comment by devJang** [comment]
안녕하세요
@Hansanghyeon, @notoriousmango
늦은 이슈 확인 죄송합니다!

현재 최신 TypeScript 핸드북을 번역하시는 분들이 계시기 때문에
그 분들과 함께하여 새롭게 작성된 번역본으로 마이그레이션할 예정이라

정적 페이지 구성이 바뀔 수 있을 것 같으니 잠시만 기다려주세요!

**Comment by guyeol** [comment]
감사합니다! 해당 이슈는 다음 릴리즈에 수정 예정입니다 https://github.com/typescript-kr/typescript-kr.github.io/pull/44
