### ISSUE TITLE
기본 타입에서 튜플을 설명하는 부분에 오역이 있습니다.

### ISSUE THREAD

**Issue by eunajjing** [typescript-kr/typescript-kr.github.io#28]
`x[3] = "world"; // 좋아요, 'string'은 'string | number'에 할당될 수 있습니다.`

이 부분의 원문은

`x[3] = "world"; // Error, Property '3' does not exist on type '[string, number]'`

이기에, 할당될 수 없다고 말함이 옳습니다.

그 외에도 

`console.log(x[5].toString()); // 좋아요, 'string' 및 'number'에 모두 'toString'이 있습니다.`

번역의 원문은

`console.log(x[5].toString()); // Error, Property '5' does not exist on type '[string, number]'.`

이기에, 5번 인덱스가 없고, 해당 인덱스가 `undefined`이므로 `toString()`을 쓸 수 없다고 번역함이 더 나을 듯 싶습니다.

**Comment by devJang** [comment]
안녕하세요!
https://github.com/typescript-kr/typescript-kr.github.io/pull/29 에 쓰레드 남겼습니다!

**Comment by Bumkeyy** [comment]
해당 이슈는 새롭게 번역된 문서를 마이그레이션하면서 해결되었습니다.

감사합니다 😄
