### ISSUE TITLE
이전 페이지 다음 페이지 넘어가는 a태그가 본문과 겹칩니다.

### ISSUE THREAD

**Issue by swtpumpkin** [typescript-kr/typescript-kr.github.io#30]
![스크린샷 2019-10-30 오후 1 22 33](https://user-images.githubusercontent.com/30548814/67828904-7ad3d280-fb18-11e9-94cf-e50141804162.png)
![스크린샷 2019-10-30 오후 1 22 19](https://user-images.githubusercontent.com/30548814/67828909-7e675980-fb18-11e9-867a-7247fa8d8999.png)
위 navigation navigation-prev / navigation navigation-next CSS class의 수정이 필요해보입니다.

**Comment by notoriousmango** [comment]
Duplicate of #27

**Comment by guyeol** [comment]
감사합니다! 해당 이슈는 다음 릴리즈에 반영됩니다 https://github.com/typescript-kr/typescript-kr.github.io/pull/44
