### ISSUE TITLE
Advanced Type / Nullable 부분에 null, undefined 를 바로 할당할수있는 문제

### ISSUE THREAD

**Issue by Joon-S** [typescript-kr/typescript-kr.github.io#33]
Advanced Type / Nullable  페이지를 읽다가 일반 변수에 null 이나 undefined 를 명시적으로 적어주지않으면 안된다고했는데 막상 타이핑하고 커맨드를 실행하니까 아래와 같은 결과가 나오는데 뭔가 잘못 이해한걸까요?

```typescript
let s = "foo"
s = null // console.log(s) -> null
s = undefined // console.log(s) -> undefined
```

**Comment by Joon-S** [comment]
아하 제가 옵션을 제대로 읽지않았네요
```
ts-node --strictNullCheck foo.ts
```

**Comment by Joon-S** [comment]
제가 `--strictNullCheck` 옵션을 해도 그냥 패스하는데...

**Comment by Bumkeyy** [comment]
@Joon-S 
코드를 실행한 환경이 어떻게 되나요?

**Comment by Bumkeyy** [comment]
해당 이슈는 장기간 활성화되지 않아서 닫겠습니다.

감사합니다. :)
