### ISSUE TITLE
번역 작업 진행 상황 관리 계획

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#40]
#### 내용
@yeonjuan @guyeol @dvlprsh 

번역 관련 작업 진행 상황을 공유 및 관리할 방법을 정해야 할 것 같습니다.

- 현재 레포처럼 `progress.md` 파일로 진행 상황 관리
- 기존 레포처럼 이슈 티켓을 생성하고, 이슈 티켓에서 체크 박스로 관리
- 프로젝트 보드를 이용하여 진행 상황 관리

3가지 정도 선택지가 있는데 의견 주시면 감사하겠습니다 :)

**Comment by dvlprsh** [comment]
> * 기존 레포처럼 이슈 티켓을 생성하고, 이슈 티켓에서 체크 박스로 관리
전 여기 한표 입니다 😄

**Comment by Bumkeyy** [comment]
- [ ] commit message lint 와 스쿼시 머지 테스트
- [ ] commit message 형식 정하기
- [ ] commit message lint 적용
