### ISSUE TITLE
Project Configuration / Compiler Options 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#51]
* 파일 경로 또는 링크: [원문](https://github.com/microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md)

* 직접 PR 하시겠습니까? (O/X): 

* 예상 완료 날짜: 

* 번역 범위:

**Comment by guyeol** [comment]
제가 번역하겠습니다~

예상 완료 날짜: 20/05/10
