### ISSUE TITLE
Project Configuration / Project References 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#52]
* 파일 경로 또는 링크: [원문](https://github.com/microsoft/TypeScript-Handbook/blob/master/pages/Project%20References.md)

* 직접 PR 하시겠습니까? (O/X): 

* 예상 완료 날짜: 

* 번역 범위:

**Comment by guyeol** [comment]
제가 할게요!
기한: 20/05/20
