### ISSUE TITLE
Project Configuration / Compiler Options in MSBuild 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#53]
* 파일 경로 또는 링크: [원문](https://github.com/microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options%20in%20MSBuild.md)

* 직접 PR 하시겠습니까? (O/X): 

* 예상 완료 날짜: 

* 번역 범위:

**Comment by guyeol** [comment]
- 직접 PR 하시겠습니까? O
- 예상 완료 날짜: 2020-06-19
