### ISSUE TITLE
Project Configuration / Intergrating with Build Tools 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#54]
* 파일 경로 또는 링크: [원문](https://github.com/microsoft/TypeScript-Handbook/blob/master/pages/Integrating%20with%20Build%20Tools.md)

* 직접 PR 하시겠습니까? (O/X): 

* 예상 완료 날짜: 

* 번역 범위:

**Comment by dvlprsh** [comment]
제가 번역하겠습니다!
- 예상 완료 날짜: 2020. 05. 13
- 번역 범위: 문서 전체
