### ISSUE TITLE
Compiler Options.md 업데이트 반영 필요

### ISSUE THREAD

**Issue by guyeol** [typescript-kr/typescript-kr.github.io#57]
* 파일 경로 또는 링크: Compiler Options.md [참고](https://github.com/microsoft/TypeScript-Handbook/commit/7825292d3679cdcd365a5167d2cac00cac91f4f6)

**Comment by Bumkeyy** [comment]
Duplicate of #51

**Comment by guyeol** [comment]
아하 포함되는군요!
