### ISSUE TITLE
릴리즈 노트 3.9 문서가 업데이트 되었는데 반영되지 않은 내용이 있어요.

### ISSUE THREAD

**Issue by yeonjuan** [typescript-kr/typescript-kr.github.io#82]
* 파일 경로 또는 링크: https://github.com/microsoft/TypeScript-Handbook/commit/51ccef10fb280284615702868412d5e223961f08

* 직접 PR 하시겠습니까? (O/X): X

* 예상 완료 날짜: X

* 번역 범위: X

**Comment by dvlprsh** [comment]
제가 하겠습니다~

- 예상 완료 날짜:  2020. 5. 27
