### ISSUE TITLE
페이지내 링크 오류

### ISSUE THREAD

**Issue by kyobeBrilliant** [typescript-kr/typescript-kr.github.io#92]
* 내용: 
번역하느라 고생이 많으십니다.

다름이 아니라 번역본을 잘 읽고 있는데, 페이지내 꽤 많은 내부링크가 깨져있더라고요. 

파일 이름 오타도 좀 있었고... 그리고 결정적으로
링크를 보면 *.md로 끝나는데, 링크 주소를 *.html로 해야 크롬 브라우저내에서 이동이 가능합니다.

이게 빌드 과정에서 원래 변환시켜주는 건데, 안되는 건지, 아니면 그냥 마크다운 문서 작성과정에서 나온 오타인지 모르겠습니다. 

다만, 포크해서 npx  gitbook serve 해보니까 로컬에서도 링크는 다 깨져있더라고요. 흐흐흐 

그리고 깃북 패키지도 최신 버젼? (3.2.3) 버젼으로 설치하니까 중괄호 두개 연속은 파싱 오류가 나더라고요.  

링크 오류가 오타면 제가 되는대로 깨진 부분 수정해서 풀요청을 날릴까 합니다. .

**Comment by dvlprsh** [comment]
@kyobeBrilliant 
안녕하세요:) 이슈 제보 감사합니다
링크 오류는 저희가 수정하겠습니다!

완료 예정일: 6월 15일

**Comment by Bumkeyy** [comment]
@kyobeBrilliant 

안녕하세요 :)
링크 버그를 제보해주셔서 감사합니다.
해당 버그는 파일명에 개행이 들어갔을 때 깃북에서 인식하지 못하는 오류가 있어서
파일명을 케밥케이스로 변경하여 해결하였고,
파일 이름 오타 또한 이번에 확인하여 잘못된 링크를 바로 잡았습니다.

앞으로도 계속 관심 가져주시길 바라며 
또 버그나 제안할 안건이 있다면
언제든지 이슈 생성해주세요 😄 

감사합니다.
