### ISSUE TITLE
Configuring Watch 번역

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#96]
* 파일 경로 또는 링크: [원문](https://github.com/typescript-kr/typescript-kr.github.io/blob/master/pages/configuring-watch.md)

**Comment by whoo3474** [comment]
후다닥 번역 진행하겠습니다. :)
문서 전체 예상 완료 날짜: 2020/08/23

**Comment by whoo3474** [comment]
1. 문단 번역 문의드립니다. :)
Use `fs.watch` which uses file system events (but might not be accurate on different OS) to get the notifications for the file changes/creation/deletion. Note that few OS eg. linux has limit on number of watches and failing to create watcher using `fs.watch` will result it in creating using `fs.watchFile`

이 부분에 대해서 여쭙고자 합니다.

파일 시스템 이벤트를 사용하는 `fs.watch`API를 사용하여 파일 변경/생성/삭제에 대한 알림을 받습니다
(`fs.watch`API는 OS마다 다르게 작동할수 있습니다.)
예를들어. 리눅스는 감시자(watcher)수에 제한이 있으며 `fs.watch`API를 사용하여 감시자를 만들지 못하면, `fs.watchFile`API를 대신 사용하여 감시자를 만들게 됩니다.

라고 번역하고 싶은데 괜찮을까요?
그런데 이렇게 그대로 번역을 하게되면 이해를 못할수가 있을것같아서, 참고를 해야하는 부분을 주석? 인용문? 으로 달고싶은데, 달아줘도 될까요?

https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener

이 부분을 모르면 그대로 받아들이기 힘든 문장인것같아서 같이 올리고 싶기에 문의드립니다.

2. watcher를 감시자라고 적어놓아도 괜찮을까요?
아니면 watcher 와 watch를 그대로 적어놔야할지 고민입니다.

**Comment by Bumkeyy** [comment]
@whoo3474 
현재 작업 진행 상황이 어떻게 되나요?
